---
title: "Simple Exponential Smoothing & Holt's seasonal method"
output:
  
  html_document: default
  keep_md: true
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(fma)
library(forecast)
```


```{r cars}
getwd()
library('knitr')
```



```{r}
#exploring the beer data set
head(beer)
```

```{r}

beer1 <- ses(beer,h=25, level = c(80,95), alpha = .1)
summary(beer1)
autoplot(beer1)
```
```{r}
beer2 <- ses(beer,h=25, level = c(80,95), alpha = .5)
summary(beer2)
autoplot(beer2)
```

```{r}
beer3 <- ses(beer,h=25, level = c(80,95), alpha = .10)
summary(beer3)
autoplot(beer3)
```

```{r}
library(forecast)
library(fma)
library(datasets)
library(ggplot2)
```

```{r}
airpass

autoplot(airpass)
```
```{r}

ses5 <- ses(airpass, h=5)
ses5

accuracy(ses5)
```
```{r}
autoplot(ses5) +
autolayer(fitted(ses5),series = "Fitted")
```

```{r}
#############################
# Holt's Linear Trend Method
#############################

holt5 <- holt(airpass,h=5)
autoplot(holt5) + 
  autolayer(fitted(holt5),series = "Fitted")

holt5damped <- holt(airpass, damped=TRUE, phi = 0.9, h=15)
```

```{r}

#Evidence suggested that the Holt's Linear Trend method 
#overestimated the predicted values. Gardner and McKenzie (1985) 
#found that dampening the trend helped accuracy

autoplot(airpass) +
  autolayer(holt5, series="Holt's method", PI=FALSE) +
  autolayer(holt5damped, series="Damped Holt's method", PI=FALSE) +
  ggtitle("Forecasts from Holt's method") + 
  guides(colour=guide_legend(title="Forecast"))
```
```{r}
##############################
# Holt's Seasonal Trend Method
##############################

hw1 <-hw(airpass, seasonal = "additive")
hw2 <-hw(airpass, seasonal = "multiplicative")

autoplot(airpass) +
  autolayer(hw1, series="HW additive forecasts", PI=FALSE) +
  autolayer(hw2, series="HW multiplicative forecasts",
            PI=FALSE) +
  #ggtitle("International visitors nights in Australia") +
  guides(colour=guide_legend(title="Forecast"))
```

